apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-memory-glibc
  namespace: py-memory
  labels:
    app: py-memory
    allocator: glibc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-memory
      allocator: glibc
  template:
    metadata:
      labels:
        app: py-memory
        allocator: glibc
    spec:
      containers:
        - name: app
          image: localhost/py-memory-glibc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
