apiVersion: v1
kind: Service
metadata:
  name: py-memory-glibc
  namespace: py-memory
  labels:
    app: py-memory
    allocator: glibc
spec:
  type: NodePort
  selector:
    app: py-memory
    allocator: glibc
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
