apiVersion: v1
kind: Service
metadata:
  name: py-memory-jemalloc
  namespace: py-memory
  labels:
    app: py-memory
    allocator: jemalloc
spec:
  type: NodePort
  selector:
    app: py-memory
    allocator: jemalloc
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081
      name: http
