apiVersion: v1
kind: Service
metadata:
  name: py-memory-glibc-malloc
  namespace: py-memory
  labels:
    app: py-memory
    allocator: glibc-malloc
spec:
  type: NodePort
  selector:
    app: py-memory
    allocator: glibc-malloc
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30083
      name: http
