apiVersion: v1
kind: Service
metadata:
  name: py-memory-production
  namespace: py-memory
  labels:
    app: py-memory
    allocator: production
spec:
  type: NodePort
  selector:
    app: py-memory
    allocator: production
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082
      name: http
